-- Run only if you are starting from an empty Supabase project.
-- If you already created these tables successfully, do NOT rerun the CREATE TABLE statements.

create table if not exists employees (
  id bigint generated by default as identity primary key,
  name text not null unique,
  role text not null check (role in ('salesperson', 'expense_reporter', 'manager')),
  telegram_user_id text unique,
  telegram_chat_id text
);

create table if not exists sales (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  submitted_at timestamptz not null default now(),
  salesperson text not null,
  customer text not null,
  project text not null check (project in ('A', 'B')),
  description text not null,
  amount numeric(12,2) not null check (amount > 0),
  proposed_richard_pct numeric(5,2) not null,
  proposed_anastasia_pct numeric(5,2) not null,
  proposed_jean_claude_pct numeric(5,2) not null,
  approved_richard_pct numeric(5,2),
  approved_anastasia_pct numeric(5,2),
  approved_jean_claude_pct numeric(5,2),
  richard_commission numeric(12,2) not null default 0,
  anastasia_commission numeric(12,2) not null default 0,
  jean_claude_commission numeric(12,2) not null default 0,
  status text not null default 'Pending approval',
  telegram_chat_id text,
  sheets_sync_status text not null default 'pending',
  notification_status text
);

create table if not exists expenses (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  submitted_at timestamptz not null default now(),
  reporter text not null,
  description text not null,
  category text not null check (category in ('Materials', 'Travel', 'Other')),
  amount numeric(12,2) not null check (amount > 0),
  proposed_allocation text not null check (proposed_allocation in ('A', 'B', 'Company overhead')),
  final_allocation text,
  status text not null,
  telegram_chat_id text,
  sheets_sync_status text not null default 'pending',
  notification_status text
);

insert into employees (name, role) values
  ('Richard "Call Me Dick" Darling', 'salesperson'),
  ('Anastasia Ferrari', 'salesperson'),
  ('Jean-Claude Bērziņš', 'salesperson'),
  ('Kevin von Whatever', 'expense_reporter'),
  ('Svetlana de Monte Carlo', 'manager')
on conflict (name) do nothing;

alter table employees enable row level security;
alter table sales enable row level security;
alter table expenses enable row level security;
